name: github-actions
on:
  push:
    branches:
    - master
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Capture the screenshot
      run: |
        export DISPLAY=":0"
        sudo apt install xvfb -y
        set -x
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "tomas@hubelbauer.net"
        git config --global user.name "Tomas Hubelbauer"
        # Wipe existing screenshot from the history
        git filter-branch --index-filter "git rm --cached --ignore-unmatch screencast-linux.apng" --prune-empty HEAD
        # Install Node dependencies
        npm install
        # Run the test which generates the screenshot
        xvfb-run --auto-servernum npm test
        # Stage the captured screenshot
        git add screencast-linux.apng README.md
        # Reset unstaged changes so that Git commit won't fail (e.g.: package-lock.json, temporary files, …)
        git checkout -- .
        # Commit the staged changes to the workflow repository
        git commit -m "Commit CI Linux screencast"
        # Authenticate with GitHub using the out of the box workflow integration PAT
        git remote set-url origin https://tomashubelbauer:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
        # Push the generated data to GitHub
        git push origin HEAD:master --force
